apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: zy881001-dev
data:
  WORDPRESS_DATABASE_NAME: wordpress
  WORDPRESS_DATABASE_USER: wpuser
  WORDPRESS_REDIS_HOST: redis
  WORDPRESS_USERNAME: admin
  WORDPRESS_EMAIL: admin@example.com